name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nickchanch/react-multi -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true nickchanch/react-test npm test

      - run: docker build -t nickchanch/multi-client ./client
      - run: docker build -t nickchanch/multi-nginx ./nginx
      - run: docker build -t nickchanch/multi-server ./server
      - run: docker build -t nickchanch/multi-worker ./worker

      - run: docker push nickchanch/multi-client
      - run: docker push nickchanch/multi-nginx
      - run: docker push nickchanch/multi-server
      - run: docker push nickchanch/multi-worker

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-gh
      #     environment_name: Multigh-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
